export const SLIDER_AUTO_PLAY_INTERVAL_MS = 3000
export const SLIDER_AUTO_PLAY_RESUME_DELAY_MS = 10000

export const SLIDER_IMAGE_TRANSITION_SECONDS = 0.55
export const SLIDER_CONTENT_TRANSITION_SECONDS = 0.35
